spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.project.store.enums

server:
  port: 8181
  address: 0.0.0.0

sa-token:
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: false
  is-log: false